# 🧠 NumPy Mastery Quiz
Responde cada pregunta directamente en las celdas de código. ¡Buena suerte!

## 1. Indexación
Extrae el valor `30` del array `arr = np.array([10, 20, 30, 40])`.

In [1]:
import numpy as np
arr = np.array([10, 20, 30, 40])
# Tu código aquí

valor30 = arr[2]
print(valor30)

valor30 = arr[-2]
print(valor30)

30
30


## 2. Slicing
Usa slicing para obtener `[20, 30]` del array anterior.

In [3]:
# Tu código aquí
a = arr[1:3]
print(a)

[20 30]


## 3. Dtype
Crea un array de enteros, pero con tipo de dato float32.

In [5]:
# Tu código aquí
arr = np.array([10, 20, 30, 40], dtype=np.float32)
print(arr, arr.dtype)

[10. 20. 30. 40.] float32


## 4. Copy vs View
Crea una copia y una vista del array `a = np.array([1, 2, 3])`. Modifica ambas y muestra si afectan al original.

In [7]:
# Tu código aquí
a = np.array([1, 2, 3], dtype=np.int8)
copia = a.copy()
vista = a.view()
print(a, a.dtype)
print(copia, copia.dtype)
print(vista, vista.dtype)

copia[0] = 10
#vista[0] = 10

print(a, a.dtype)
print(copia, copia.dtype)
print(vista, vista.dtype)

[1 2 3] int8
[1 2 3] int8
[1 2 3] int8
[1 2 3] int8
[10  2  3] int8
[1 2 3] int8


## 5. Array Shape
Crea un array 3x2 y muestra su forma con `.shape` y número de dimensiones con `.ndim`.

In [11]:
# Tu código aquí
arr = np.array([[1, 3], [1, 3], [2, 3]])
print(arr)

print(arr.shape)
print(arr.ndim)

[[1 3]
 [1 3]
 [2 3]]
(3, 2)
2


## 6. Reshape
Transforma un array 1D de 6 elementos en uno 2D de 2x3.

In [14]:
# Tu código aquí
arr = np.array([1, 2, 3, 4, 5, 6])
print(arr)

#transdormarlo en una matriz de 2x3
arr = arr.reshape(2, 3)
print(arr)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


## 7. Broadcasting
Suma un array `x = np.array([0, 1])` con `y = np.array([[10], [20], [30]])` usando broadcasting.

In [15]:
# Tu código aquí
#Suma un array `x = np.array([0, 1])` con `y = np.array([[10], [20], [30]])` usando broadcasting.
x = np.array([0, 1])
y = np.array([[10], [20], [30]])
print(x.shape)
print(y.shape)
print(x + y)


(2,)
(3, 1)
[[10 11]
 [20 21]
 [30 31]]


## 8. Data Casting
Convierte un array float en uno entero usando `.astype()`.

In [ ]:
# Tu código aquí

## 9. Indexación 2D
Accede al número 7 del siguiente array:
```python
np.array([[1,2,3], [4,5,6], [7,8,9]])```

In [18]:
# Tu código aquí
# # np.array([[1,2,3], [4,5,6], [7,8,9]])```

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr)

Numero7 = arr[2, 0]
print(Numero7)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
7


## 10. Extra (Avanzado)
Explica con una línea de comentario cuándo usarías `.copy()` y cuándo `.view()`.

In [ ]:
# Tu comentario aquí